name: GParted Live customization build script

on: [push]
  
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '10 00 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install prerequisites
      run: |
        sudo apt -qq update; sudo apt -qq install squashfs-tools isolinux xorriso unzip zip
        
    - name: Get GParted live zip
      run: |
        time wget -nv https://freefr.dl.sourceforge.net/project/gparted/gparted-live-stable/1.4.0-5/gparted-live-1.4.0-5-amd64.zip
      shell: bash
    - name: Prepare custom env
      run: |
        mkdir ~/zip-tmp ~/squashfs-tmp
        unzip -q gparted-live-1.4.0-5-amd64.zip -d ~/zip-tmp
        cp ~/zip-tmp/live/filesystem.squashfs ~/squashfs-tmp
        cd ~/squashfs-tmp; sudo unsquashfs filesystem.squashfs
        
        sudo mount --bind /proc squashfs-root/proc/
        sudo mount --bind /sys squashfs-root/sys/
        sudo mount --bind /dev squashfs-root/dev/
    
    - name: Get GParted Live zip and customize it
      run: |
        set -xe
        cd ~/squashfs-tmp; 
        sudo --preserve-env chroot squashfs-root/ apt update
        sudo --preserve-env chroot squashfs-root/ apt search firefox
        exit(1)
      
        #echo "nameserver 8.8.8.8" > /etc/resolv.conf
        #apt-get update; apt-get install firefox-esr
        #exit
      shell: bash
    
    - name: Build custom ISO
      run: |
        sudo mksquashfs squashfs-root filesystem.squashfs.new -b 1024k -comp xz -Xbcj x86 -e boot
        sudo cp filesystem.squashfs.new ~/zip-tmp/live/filesystem.squashfs
        cd ~/zip-tmp ; sudo zip -r ../gparted-live.new.zip ./*
        xorriso -as mkisofs -R -r -J -joliet-long -l -cache-inodes -iso-level 3 -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -partition_offset 16 -A 'GParted live CD' -b syslinux/isolinux.bin -c syslinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot --efi-boot boot/grub/efi.img -isohybrid-gpt-basdat -isohybrid-apm-hfsplus ./ > /tmp/gparted-live.iso
