name: GParted Live customization build script

on: workflow_dispatch
  
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '10 00 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install prerequisites
      run: |
        set -xe
        sudo apt -y -qq -o=Dpkg::Use-Pty=0 update ; sudo apt -y -qq -o=Dpkg::Use-Pty=0 upgrade ; sudo apt -y -qq -o=Dpkg::Use-Pty=0 install squashfs-tools isolinux xorriso unzip zip
        #sudo apt -y -qq -o=Dpkg::Use-Pty=0 install squashfs-tools isolinux xorriso unzip zip
        
    - name: Get GParted Live zip
      run: |
        set -xe
        
        ROOT_DIR="/tmp/"
        echo "ROOT_DIR=$ROOT_DIR" >> $GITHUB_ENV
        
        cd $ROOT_DIR
        
        GPARTED_BASE_ZIP_URL="https://freefr.dl.sourceforge.net/project/gparted/gparted-live-stable/1.5.0-6/gparted-live-1.5.0-6-amd64.zip"
        GPARTED_BASE_NAME=$(basename $GPARTED_BASE_ZIP_URL) .zip
        time wget -nv "$GPARTED_BASE_ZIP_URL"
        
        echo "GPARTED_BASE_NAME=$GPARTED_BASE_NAME" >> $GITHUB_ENV
        
        #time wget -nv https://freefr.dl.sourceforge.net/project/gparted/gparted-live-stable/1.4.0-5/gparted-live-1.4.0-5-amd64.zip
        #time wget -nv https://altushost-swe.dl.sourceforge.net/project/gparted/gparted-live-stable/1.4.0-5/gparted-live-1.4.0-5-amd64.zip

        exit(1)

      shell: bash
    
    - name: Prepare custom env
      run: |
        set -xe
        
        mkdir ~/zip-tmp ~/squashfs-tmp
        unzip -q gparted-live-1.4.0-5-amd64.zip -d ~/zip-tmp
        cp ~/zip-tmp/live/filesystem.squashfs ~/squashfs-tmp
        cd ~/squashfs-tmp; sudo unsquashfs filesystem.squashfs
        
        sudo mount --bind /proc squashfs-root/proc/
        sudo mount --bind /sys squashfs-root/sys/
        sudo mount --bind /dev squashfs-root/dev/
        sudo mount --bind /dev/pts squashfs-root/dev/pts/
        
      shell: bash
    
    - name: Customize env
      run: |
        set -xe
        
        ls -al ~/squashfs-tmp;
        cd ~/squashfs-tmp;
        echo nameserver 8.8.8.8| sudo tee squashfs-root/etc/resolv.conf
        
        sudo --preserve-env chroot squashfs-root/ apt -y -qq update
        
        DEBIAN_FRONTEND=noninteractive sudo --preserve-env chroot squashfs-root/ apt -y -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install wget mlocate git kbd vim strace ltrace git net-tools lsof python3-pip dkms make bzip2 curl dnsutils openssh-server openssh-client bmon nmon htop gzip coreutils dos2unix util-linux iptables jq less nmap parallel sed grep sqlite3 ftp tzdata vlan python3-virtualenv virtualenvwrapper libpq-dev libpcap-dev libssl-dev python3 python3-dev xxd colordiff findutils zutils nfs-common ntfs-3g pigz xrdp cifs-utils smbclient openssl pv subversion tar telnet tcpdump tshark traceroute vbindiff usbutils whois xz-utils rclone
        DEBIAN_FRONTEND=noninteractive sudo --preserve-env chroot squashfs-root/ apt -y -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" full-upgrade
        DEBIAN_FRONTEND=noninteractive sudo --preserve-env chroot squashfs-root/ apt -y -qq autoremove --purge
        DEBIAN_FRONTEND=noninteractive sudo --preserve-env chroot squashfs-root/ apt -y -qq clean
        DEBIAN_FRONTEND=noninteractive sudo --preserve-env chroot squashfs-root/ apt -y -qq autoclean
               
        sudo --preserve-env chroot squashfs-root/ dpkg --get-selections > ~/zip-tmp/live/filesystem.packages
        
        sudo --preserve-env chroot squashfs-root/ systemctl stop rpcbind.socket
        sudo --preserve-env chroot squashfs-root/ systemctl mask rpcbind.socket
        
        sudo --preserve-env chroot squashfs-root/ systemctl stop rpcbind
        sudo --preserve-env chroot squashfs-root/ systemctl mask rpcbind
        
        sudo --preserve-env chroot squashfs-root/ systemctl stop xrdp
        sudo --preserve-env chroot squashfs-root/ systemctl mask xrdp
        
        sudo --preserve-env chroot squashfs-root/ systemctl stop systemd-resolved.service
        sudo --preserve-env chroot squashfs-root/ systemctl mask systemd-resolved.service

        sudo --preserve-env chroot squashfs-root/ systemctl stop tftpd-hpa.service
        sudo --preserve-env chroot squashfs-root/ systemctl mask tftpd-hpa.service
        
        sudo rm -f squashfs-root/etc/resolv.conf
  
      shell: bash
    
    - name: Unprep the custom env
      run: |
        set -xe
        
        cd ~/squashfs-tmp;
        
        echo "[+] findmnt before unmount"
        findmnt
        echo
        sudo umount squashfs-root/proc/
        sudo umount squashfs-root/sys/
        sudo umount squashfs-root/dev/pts/
        sudo umount squashfs-root/dev/
        
        echo "[+] findmnt after unmount"
        findmnt
        echo
                
      shell: bash
    
    - name: Build custom ISO
      run: |
        set -xe
        
        sudo cp -f $GITHUB_WORKSPACE/_resources/Gsplash.png ~/zip-tmp/syslinux/Gsplash.png
        sudo cp -f $GITHUB_WORKSPACE/_resources/Gsplash.png ~/zip-tmp/boot/grub/Gsplash.png
                
        cd ~/squashfs-tmp
        sudo mksquashfs squashfs-root filesystem.squashfs.new -b 1024k -comp xz -Xbcj x86 -e boot
        sudo cp filesystem.squashfs.new ~/zip-tmp/live/filesystem.squashfs
        
        sudo find ~/zip-tmp/ -type f -exec sha256sum {} \; 1>/tmp/sha256sum.txt
        sudo cp -f /tmp/sha256sum.txt ~/zip-tmp/sha256sum.txt
        
        cd ~/zip-tmp ; sudo zip -r ../gparted-live.new.zip ./*
        xorriso -as mkisofs -R -r -J -joliet-long -l -cache-inodes -iso-level 3 -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -partition_offset 16 -A 'GParted live CD' -b syslinux/isolinux.bin -c syslinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot --efi-boot boot/grub/efi.img -isohybrid-gpt-basdat -isohybrid-apm-hfsplus ./ > "/tmp/gparted-live-1.4.0-5-amd64-maaaaz-edition-$(date '+%Y%m%d').iso"
        ls -al /tmp/gparted*
        
      shell: bash
